[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["Qin-shihuang <0.0@owo.li>"]

[dependencies]
sbi = { path = "../crates/sbi" }
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2
lto = true
