[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["Qin-shihuang <0.0@owo.li>"]

[dependencies]
sbi = { path = "../crates/sbi" }

log = "0.4.14"
spin = "0.9.8"

[features]
default = ["smp"]

smp = []