[build]
target = "riscv64gc-unknown-none-elf"


[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -bios default -nographic -smp 4 -m 256M -kernel"
rustflags = [
    "-Clink-arg=-Tsrc/linker.lds",
    "-Cforce-frame-pointers=yes"
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]